version: "3.9"

services:
  beelzebub:
    build: .
    #network_mode: host # Not work on Mac OS
    container_name: beelzebub
    restart: always
    ports: # Remove me, if you use configuration network_mode: host
      - "22:22"
      - "2222:2222"
      - "8080:8080"
      - "8081:8081"
      - "80:80"
      - "3306:3306"
      - "2112:2112" # Prometheus openmetrics
    environment:
      RABBITMQ_URI: ${RABBITMQ_URI}
      BEELZEBUB_LLM_MODEL: "ollama"
      BEELZEBUB_LLM_HOST: "http://localhost:11434/api/chat"
      BEELZEBUB_OLLAMA_MODEL: "llama3.1"
      #BEELZEBUB_LLM_MODEL: "gpt4-o"
      #BEELZEBUB_OPENAISECRETKEY: "sk-proj-123456"
#    volumes:
#      - "./configurations:/configurations"